// ===== SCRAPMART DATA =====

const CATEGORIES = [
  {
    id: "metal",
    name: "Metal",
    icon: "fas fa-cog",
    color: "#f59e0b",
    desc: "Iron, steel, copper, aluminium & all metal scrap",
    baseRate: 28,
    coinPer10kg: 15,
  },
  {
    id: "plastic",
    name: "Plastic",
    icon: "fas fa-bottle-water",
    color: "#3b82f6",
    desc: "PET bottles, HDPE, PVC, polythene & other plastics",
    baseRate: 12,
    coinPer10kg: 10,
  },
  {
    id: "paper",
    name: "Paper",
    icon: "fas fa-newspaper",
    color: "#10b981",
    desc: "Newspapers, cardboard, books, office paper waste",
    baseRate: 8,
    coinPer10kg: 8,
  },
  {
    id: "ewaste",
    name: "E-Waste",
    icon: "fas fa-microchip",
    color: "#8b5cf6",
    desc: "Mobiles, laptops, PCBs, wires & electronic parts",
    baseRate: 50,
    coinPer10kg: 30,
  },
  {
    id: "glass",
    name: "Glass",
    icon: "fas fa-wine-bottle",
    color: "#06b6d4",
    desc: "Glass bottles, broken glass, mirrors & glassware",
    baseRate: 5,
    coinPer10kg: 5,
  },
  {
    id: "rubber",
    name: "Rubber",
    icon: "fas fa-circle",
    color: "#ef4444",
    desc: "Tyres, tubes, rubber hoses & industrial rubber",
    baseRate: 10,
    coinPer10kg: 8,
  },
  {
    id: "textile",
    name: "Textile",
    icon: "fas fa-shirt",
    color: "#f97316",
    desc: "Old clothes, fabric waste, rags & textile scraps",
    baseRate: 6,
    coinPer10kg: 6,
  },
  {
    id: "wood",
    name: "Wood",
    icon: "fas fa-tree",
    color: "#84cc16",
    desc: "Furniture, plywood, wooden pallets & timber waste",
    baseRate: 4,
    coinPer10kg: 4,
  },
];

const COMPANIES = [
  {
    id: "c1",
    name: "GreenCycle India Pvt. Ltd.",
    logo: "fas fa-recycle",
    logoColor: "#10b981",
    location: "Hadapsar, Pune",
    lat: 18.5018,
    lng: 73.9258,
    status: "Active",
    rating: 4.8,
    reviews: 234,
    categories: ["Metal", "Plastic", "Paper"],
    rates: { metal: 30, plastic: 13, paper: 9, ewaste: 0, glass: 0, rubber: 11, textile: 0, wood: 0 },
    coinBonus: { metal: 18, plastic: 12, paper: 9, ewaste: 0, glass: 0, rubber: 9, textile: 0, wood: 0 },
    minQty: 5,
    pickup: true,
    desc: "Leading eco-recycling company with 10+ years experience. Doorstep pickup available across Pune.",
    badge: "Top Rated",
    badgeColor: "#f59e0b",
    coupon: { code: "GREEN20", offer: "20% OFF on next pickup", minPurchase: "₹500" },
    phone: "+91 98765 11001",
    openTime: "Mon-Sat 8AM–6PM",
  },
  {
    id: "c2",
    name: "MetalKing Recyclers",
    logo: "fas fa-industry",
    logoColor: "#f59e0b",
    location: "Bhosari MIDC, Pune",
    lat: 18.6279,
    lng: 73.8408,
    status: "Active",
    rating: 4.6,
    reviews: 189,
    categories: ["Metal", "E-Waste", "Rubber"],
    rates: { metal: 32, plastic: 0, paper: 0, ewaste: 55, glass: 0, rubber: 12, textile: 0, wood: 0 },
    coinBonus: { metal: 20, plastic: 0, paper: 0, ewaste: 35, glass: 0, rubber: 10, textile: 0, wood: 0 },
    minQty: 10,
    pickup: true,
    desc: "Specialised in metal & e-waste recycling. Best rates for copper, aluminium and electronic boards.",
    badge: "Best Metal Rates",
    badgeColor: "#f59e0b",
    coupon: { code: "METAL15", offer: "Flat ₹150 OFF", minPurchase: "₹1000" },
    phone: "+91 98765 22002",
    openTime: "Mon-Sat 9AM–5PM",
  },
  {
    id: "c3",
    name: "EcoWave Solutions",
    logo: "fas fa-water",
    logoColor: "#3b82f6",
    location: "Wakad, Pune",
    lat: 18.5993,
    lng: 73.7614,
    status: "Active",
    rating: 4.5,
    reviews: 156,
    categories: ["Plastic", "Glass", "Textile"],
    rates: { metal: 0, plastic: 14, paper: 0, ewaste: 0, glass: 6, rubber: 0, textile: 7, wood: 0 },
    coinBonus: { metal: 0, plastic: 14, paper: 0, ewaste: 0, glass: 6, rubber: 0, textile: 7, wood: 0 },
    minQty: 3,
    pickup: true,
    desc: "Focused on plastic & textile recycling. Accepting all types of plastic and fabric waste.",
    badge: "Plastic Specialist",
    badgeColor: "#3b82f6",
    coupon: { code: "ECOWAVE10", offer: "10% OFF + Free Pickup", minPurchase: "₹300" },
    phone: "+91 98765 33003",
    openTime: "Mon-Sun 7AM–7PM",
  },
  {
    id: "c4",
    name: "TechReclaim E-Waste",
    logo: "fas fa-microchip",
    logoColor: "#8b5cf6",
    location: "Hinjewadi IT Park, Pune",
    lat: 18.5912,
    lng: 73.7389,
    status: "Active",
    rating: 4.9,
    reviews: 312,
    categories: ["E-Waste", "Metal"],
    rates: { metal: 29, plastic: 0, paper: 0, ewaste: 60, glass: 0, rubber: 0, textile: 0, wood: 0 },
    coinBonus: { metal: 17, plastic: 0, paper: 0, ewaste: 40, glass: 0, rubber: 0, textile: 0, wood: 0 },
    minQty: 1,
    pickup: true,
    desc: "Certified e-waste recycler. Accepts all electronics, offers data destruction certificates.",
    badge: "🏆 Top Rated",
    badgeColor: "#8b5cf6",
    coupon: { code: "TECH25", offer: "25% OFF next e-waste drop", minPurchase: "₹200" },
    phone: "+91 98765 44004",
    openTime: "Mon-Sat 9AM–8PM",
  },
  {
    id: "c5",
    name: "PaperWorks Recycling",
    logo: "fas fa-newspaper",
    logoColor: "#10b981",
    location: "Kothrud, Pune",
    lat: 18.5074,
    lng: 73.8077,
    status: "Active",
    rating: 4.3,
    reviews: 98,
    categories: ["Paper", "Wood", "Textile"],
    rates: { metal: 0, plastic: 0, paper: 10, ewaste: 0, glass: 0, rubber: 0, textile: 7, wood: 5 },
    coinBonus: { metal: 0, plastic: 0, paper: 10, ewaste: 0, glass: 0, rubber: 0, textile: 7, wood: 5 },
    minQty: 5,
    pickup: false,
    desc: "Best paper & cardboard rates in Pune. Drop-off facility available 7 days a week.",
    badge: "Paper Expert",
    badgeColor: "#10b981",
    coupon: { code: "PAPER50", offer: "₹50 Bonus on 50kg+", minPurchase: "₹150" },
    phone: "+91 98765 55005",
    openTime: "Mon-Sun 6AM–9PM",
  },
  {
    id: "c6",
    name: "Radiant Scrap Hub",
    logo: "fas fa-star",
    logoColor: "#ef4444",
    location: "Pimpri, Pune",
    lat: 18.6217,
    lng: 73.7999,
    status: "Inactive",
    rating: 4.1,
    reviews: 74,
    categories: ["Metal", "Rubber", "Glass"],
    rates: { metal: 27, plastic: 0, paper: 0, ewaste: 0, glass: 5, rubber: 10, textile: 0, wood: 0 },
    coinBonus: { metal: 15, plastic: 0, paper: 0, ewaste: 0, glass: 5, rubber: 8, textile: 0, wood: 0 },
    minQty: 8,
    pickup: true,
    desc: "General scrap buyer with competitive prices for metal, rubber and glass waste.",
    badge: "Temporarily Inactive",
    badgeColor: "#9ca3af",
    coupon: { code: "RADIANT10", offer: "10% OFF all scrap", minPurchase: "₹400" },
    phone: "+91 98765 66006",
    openTime: "Mon-Fri 10AM–4PM",
  },
  {
    id: "c7",
    name: "CleanEarth Agro Waste",
    logo: "fas fa-leaf",
    logoColor: "#84cc16",
    location: "Baner, Pune",
    lat: 18.5600,
    lng: 73.7700,
    status: "Active",
    rating: 4.4,
    reviews: 121,
    categories: ["Wood", "Paper", "Rubber"],
    rates: { metal: 0, plastic: 0, paper: 9, ewaste: 0, glass: 0, rubber: 11, textile: 0, wood: 5 },
    coinBonus: { metal: 0, plastic: 0, paper: 8, ewaste: 0, glass: 0, rubber: 10, textile: 0, wood: 5 },
    minQty: 5,
    pickup: true,
    desc: "Specialised in organic & agro waste recycling. Also accepts paper and wood.",
    badge: "Eco Certified",
    badgeColor: "#84cc16",
    coupon: { code: "CLEAN30", offer: "Free Pickup + ₹30 Bonus", minPurchase: "₹250" },
    phone: "+91 98765 77007",
    openTime: "Mon-Sat 8AM–6PM",
  },
  {
    id: "c8",
    name: "AllScrap Express",
    logo: "fas fa-truck",
    logoColor: "#f97316",
    location: "Wagholi, Pune",
    lat: 18.5589,
    lng: 73.9800,
    status: "Active",
    rating: 4.2,
    reviews: 87,
    categories: ["Metal", "Plastic", "Paper", "E-Waste", "Glass", "Rubber", "Textile", "Wood"],
    rates: { metal: 26, plastic: 11, paper: 7, ewaste: 48, glass: 4, rubber: 9, textile: 5, wood: 4 },
    coinBonus: { metal: 14, plastic: 9, paper: 7, ewaste: 28, glass: 4, rubber: 7, textile: 5, wood: 4 },
    minQty: 2,
    pickup: true,
    desc: "All-in-one scrap buyer. Accepts every category with express doorstep pickup within 2 hours.",
    badge: "All Categories",
    badgeColor: "#f97316",
    coupon: { code: "ALLSCRAP5", offer: "5% extra on all scrap", minPurchase: "₹100" },
    phone: "+91 98765 88008",
    openTime: "Mon-Sun 7AM–9PM",
  },
];

// Coin-to-coupon threshold
const COIN_THRESHOLD = 500;
